[GLOBAL]
pants_version = "2.30.0"
backend_packages = [
    "pants.backend.python",
    "pants.backend.docker",
]

[source]
root_patterns = ["/"]

[python]
interpreter_constraints = ["CPython>=3.11,<3.13"]

[python-infer]
use_rust_parser = true

[docker]
default_repository = "ercot-lmp"

[anonymous-telemetry]
enabled = false
